/// Generated by spider on 2025-10-26 01:26:52.164218

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:card_mind/core/constants/icon_path.dart';

void main() {
  test('icon_path assets test', () {
    expect(File(IconPath.appIcon).existsSync(), isTrue);
    expect(File(IconPath.iconHistory).existsSync(), isTrue);
    expect(File(IconPath.iconTrash).existsSync(), isTrue);
    expect(File(IconPath.iconWow).existsSync(), isTrue);
  });
}
