/// Generated by spider on 2025-10-07 21:29:49.643280

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:card_mind/core/constants/icon_path.dart';

void main() {
  test('icon_path assets test', () {
    expect(File(IconPath.iconBag).existsSync(), isTrue);
    expect(File(IconPath.iconDone).existsSync(), isTrue);
    expect(File(IconPath.iconGoogle).existsSync(), isTrue);
    expect(File(IconPath.iconHome).existsSync(), isTrue);
    expect(File(IconPath.iconLogout).existsSync(), isTrue);
    expect(File(IconPath.iconMenu).existsSync(), isTrue);
    expect(File(IconPath.iconSun).existsSync(), isTrue);
  });
}
