/// Generated by spider on 2025-10-12 00:51:45.823002

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:card_mind/core/constants/image_path.dart';

void main() {
  test('image_path assets test', () {});
}
