/// Generated by spider on 2025-10-07 21:29:49.672399

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:card_mind/core/constants/image_path.dart';

void main() {
  test('image_path assets test', () {
    expect(File(ImagePath.imgForgotPassword).existsSync(), isTrue);
  });
}
