/// Generated by spider on 2025-10-26 01:26:52.198526

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:card_mind/core/constants/image_path.dart';

void main() {
  test('image_path assets test', () {});
}
