// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbLSL0yLnkGlqGRFJ94ONbB17b5ZLPb3g',
    authDomain: 'card-mind.firebaseapp.com',
    projectId: 'card-mind',
    storageBucket: 'card-mind.firebasestorage.app',
    messagingSenderId: '154797023123',
    appId: '1:154797023123:web:8e8c20e1fdda5f1a589266',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcIR9YU0gvWV1vKNNC7NU-7C1yPcSrAOc',
    appId: '1:154797023123:android:9f5b1467c3a854cf589266',
    messagingSenderId: '154797023123',
    projectId: 'card-mind',
    storageBucket: 'card-mind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE8JwNSAgCjbZ65aA7xa7Pn592Jr_JML0',
    appId: '1:154797023123:ios:9a67b8277e0b76f9589266',
    messagingSenderId: '154797023123',
    projectId: 'card-mind',
    storageBucket: 'card-mind.firebasestorage.app',
    iosBundleId: 'com.nguyenduc.cardMind',
  );
}
