// Generated by spider on 2025-10-26 01:26:52.073873

class IconPath {
  IconPath._();

  static const String appIcon = 'assets/icons/app_icon.png';
  static const String iconHistory = 'assets/icons/icon_history.svg';
  static const String iconTrash = 'assets/icons/icon_trash.svg';
  static const String iconWow = 'assets/icons/icon_wow.svg';
}
