// Generated by spider on 2025-10-12 00:51:45.666819

class IconPath {
  IconPath._();

  static const String appIcon = 'assets/icons/app_icon.png';
  static const String iconWow = 'assets/icons/icon_wow.svg';
}
